/**
 * basic images
 */
export const Images = {
  Logo: require('../assets/logo.png'),
  Play: require('../assets/img/play.png'),
  PlayHeader: require('../assets/img/play-header.png'),
  GoogleLogin: require('../assets/img/googleLogin.png'),
  Email: require('../assets/img/email.png'),
  ImageFooter: require('../assets/img/imagefooter.png'),
  Service1: require('../assets/img/1.png'),
  Service2: require('../assets/img/2.png'),
  Service3: require('../assets/img/3.png'),
  Star: require('../assets/img/sparkles.png'),
  Phone: require('../assets/img/phone.png'),
  Brand: require('../assets/img/brand.png'),
  Brand1: require('../assets/img/brand1.png'),
  About1: require('../assets/img/about1.png'),
  About2: require('../assets/img/about2.png'),
  Brand2: require('../assets/img/brand2.png'),
  ContactUs: require('../assets/img/contactus.png'),
  BrandDash1: require('../assets/img/brandimg1.png'),
  BrandDash2: require('../assets/img/chronotrack_registration.png'),
  Avatar: require('../assets/img/user.png'),
  Avatar1: require('../assets/img/dp.png'),
  PaymentVisa: require('../assets/img/paymentvisa.png'),
  Payments: require('../assets/img/payments.png'),
  ThumbDown: require('../assets/img/thumb-down.png'),
  Chat: require('../assets/img/chat.png'),
  AthletesImg: require('../assets/img/run.png'),
  SmallPlay: require('../assets/img/small-play.png'),
  Password: require('../assets/img/passwordicon.png'),
  UserIcon: require('../assets/img/userIcon.png'),
  GoogleButton: require('../assets/img/google.png'),
  Footer: require('../assets/img/footer.png'),
  Calendar: require('../assets/img/calendar.png'),
}
